#! /bin/bash -e

#python dependencies
sudo apt-get -y install python-numpy python-dev python-pip python-wheel

#c++ dependencies
sudo apt-get -y install \
     libprotobuf-dev \
     libleveldb-dev \
     libhdf5-serial-dev \
     protobuf-compiler \
     libgflags-dev \
     libgoogle-glog-dev
     sudo apt-get install -f

#jdk dependency for bazel
 export DEBIAN_FRONTEND=noninteractive
 yes "" | sudo add-apt-repository ppa:webupd8team/java
 sudo apt-get update
 echo "oracle-java8-installer shared/accepted-oracle-license-v1-1 select true" | sudo debconf-set-selections
 sudo apt-get -y install oracle-java8-installer
 sudo apt-get -y install oracle-java8-set-default
 sudo apt-get install -f

#installing bazel
 echo "deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
 curl https://bazel.build/bazel-release.pub.gpg | sudo apt-key add -
 sudo apt-get update
 sudo apt-get -y install bazel
 sudo apt-get install -f

