#! /bin/bash -e

#python dependencies
sudo apt-get -y install python-numpy python-dev python-pip python-wheel

#c++ dependencies
sudo apt-get -y install \
     libprotobuf-dev \
     libleveldb-dev \
     libhdf5-serial-dev \
     protobuf-compiler \
     libgflags-dev \
     libgoogle-glog-dev
     sudo apt-get install -f

# #installing bazel
BAZEL_PKG="bazel-0.5.4-installer-linux-x86_64.sh"
rm -f bazel-*
wget https://github.com/bazelbuild/bazel/releases/download/0.5.4/${BAZEL_PKG}
sudo chmod a+x ./${BAZEL_PKG}
sudo ./${BAZEL_PKG}
bazel version